# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKLogDemo' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for DKLogDemo
  pod 'DKLog', :path=>'../'

  target 'DKLogDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DKLogDemoUITests' do
    # Pods for testing
  end

end
